[project]
name = 'Blockchain-Based-Logistics-Cross-Docking-Operations'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.dock-scheduling]
path = 'contracts/dock-scheduling.clar'
clarity_version = 2
epoch = 2.5

[contracts.efficiency-optimization]
path = 'contracts/efficiency-optimization.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
